# Generated by Django 4.0.4 on 2022-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loltest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
