# Generated by Django 4.0.4 on 2022-06-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loltest', '0002_games_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='kda',
        ),
        migrations.AddField(
            model_name='games',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='kills',
            field=models.IntegerField(default=0),
        ),
    ]
