# Generated by Django 4.0.4 on 2022-06-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loltest', '0003_remove_games_kda_games_assists_games_deaths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='update_date',
            field=models.DateField(default='2010-01-01'),
        ),
    ]
